sudo: false
language: node_js
node_js:
- '8'
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- sudo apt-get install -y libasound2-dev
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
after_success:
  - npm pack
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "sverigesradio-*.tgz"
    skip_cleanup: true
    on:
      node: '8'
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "ollebostr@gmail.com"
    api_key: $NPM_TOKEN
    on:
      node: '8'
      tags: true
